//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("connection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;text&quot;: &quot;@AlertTitle&quot;,
        ///    &quot;attachments&quot;: [
        ///        {
        ///            &quot;title&quot;: &quot;@Subject&quot;,
        ///            &quot;fields&quot;: [
        ///                {
        ///                    &quot;title&quot;: &quot;&quot;,
        ///                    &quot;value&quot;: &quot;@Message&quot;,
        ///                    &quot;Short&quot;: &quot;True&quot;
        ///                }
        ///            ],
        ///            &quot;author_name&quot;: &quot;@ProcedureGuatemalaDigital.com/&quot;,
        ///            &quot;author_icon&quot;: &quot;https://guatemaladigital.com:3001/images/favicon.ico&quot;
        ///        }
        ///    ]
        ///}.
        /// </summary>
        internal static string structureSlack {
            get {
                return ResourceManager.GetString("structureSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style = &quot;width:65%; border-width:1px;  border-style:solid&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td&gt;
        ///            &lt;img src=&quot;https://guatemaladigital.com:3001/images/poster_correo.jpg&quot; alt=&quot;Loading image...&quot; width=&quot;65%&quot;&gt;
        ///            &lt;img src=&quot;https://guatemaladigital.com:3001/images/CorreoEncabezado.jpg&quot; alt=&quot;Loading image...&quot; width=&quot;65%&quot;&gt;
        ///            @body
        ///            &lt;img src=&quot;https://guatemaladigital.com:3001/images/CorreoEncabezado.jpg&quot; alt=&quot;Loading image...&quot; width=&quot;65%&quot;&gt;
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string TemplatePrincipalMail {
            get {
                return ResourceManager.GetString("TemplatePrincipalMail", resourceCulture);
            }
        }
    }
}
